-- Heartbeats table for the GitHub Actions inactivity ping.
--
-- Free-tier Supabase projects get paused after 7 days of inactivity, and
-- the previous heartbeat (anon SELECT + intentionally-failing auth POST)
-- was still generating "your project has been inactive" warnings from
-- Supabase — evidently their heuristic wants writes, not just reads. This
-- table gives the GitHub Action a place to do a real INSERT so the DB
-- clearly sees activity.
--
-- Anyone (anon) can INSERT with source='github-heartbeat' and no other
-- fields. That's tight enough that a rogue caller can only spam this one
-- table with tagged rows, which we can purge with a WHERE.
--
-- Reads are limited to authenticated users so the app can render a
-- health widget later if we want to; anon can't scan the table.

create table if not exists public.heartbeats (
  id bigint generated by default as identity primary key,
  source text not null,
  pinged_at timestamptz not null default now()
);

create index if not exists heartbeats_pinged_at_idx on public.heartbeats (pinged_at desc);

alter table public.heartbeats enable row level security;

-- Anon: INSERT only, and only rows tagged 'github-heartbeat'.
create policy heartbeats_anon_insert
  on public.heartbeats
  for insert
  to anon
  with check (source = 'github-heartbeat');

-- Authenticated: full read for future dashboards / admin queries.
create policy heartbeats_authenticated_read
  on public.heartbeats
  for select
  to authenticated
  using (true);
