-- Paperplate initial schema.
-- Mirrors the SQLite schema at user_version=10 from apps/desktop/src/lib/db/migrations.ts,
-- collapsed into a single Postgres migration. The single-shared-account model means
-- RLS is enforced only against the authenticated role; there are no per-user partitions.

-- ---------------------------------------------------------------------------
-- Recipes
-- ---------------------------------------------------------------------------

create table public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  source_url text,
  image_path text,                       -- storage object key, e.g. "recipe-images/<hash>.<ext>"
  base_servings integer not null default 4,
  preferred_servings integer,
  prep_min integer,
  cook_min integer,
  total_min integer,
  difficulty text check (difficulty in ('easy', 'medium', 'hard')),
  rating integer check (rating between 0 and 5),
  last_cooked_at timestamptz,
  notes text,
  raw_html text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index recipes_title_idx on public.recipes (title);
create index recipes_last_cooked_idx on public.recipes (last_cooked_at);

create table public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  position integer not null,
  raw_text text not null,
  quantity double precision,
  unit text,
  item_canonical text not null,
  item_display text not null,
  preparation text,
  is_optional boolean not null default false,
  section_name text                       -- optional sub-recipe header, e.g. "Frosting"
);

create index recipe_ingredients_recipe_idx on public.recipe_ingredients (recipe_id);
create index recipe_ingredients_canonical_idx on public.recipe_ingredients (item_canonical);

create table public.recipe_steps (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  position integer not null,
  text text not null,
  section_name text
);

create index recipe_steps_recipe_idx on public.recipe_steps (recipe_id);

-- ---------------------------------------------------------------------------
-- Categories — tags grouped by axis (cuisine, protein, type, cooking_method, …)
-- ---------------------------------------------------------------------------

create table public.categories (
  id bigint generated by default as identity primary key,
  kind text not null check (
    kind in ('cuisine', 'protein', 'type', 'cooking_method', 'effort', 'tag', 'dietary')
  ),
  name text not null,
  sort_order integer not null default 0,
  unique (kind, name)
);

create index categories_kind_idx on public.categories (kind, sort_order);

create table public.recipe_categories (
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  primary key (recipe_id, category_id)
);

-- ---------------------------------------------------------------------------
-- Meal plans
-- ---------------------------------------------------------------------------

create table public.meal_plans (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date not null,
  created_at timestamptz not null default now()
);

create table public.meal_plan_slots (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.meal_plans(id) on delete cascade,
  date date not null,
  slot text not null check (slot in ('breakfast', 'lunch', 'dinner')),
  -- legacy single-recipe column kept for compatibility with older queries;
  -- new code reads from meal_plan_slot_recipes.
  recipe_id bigint references public.recipes(id) on delete set null,
  scaled_servings integer,
  is_locked boolean not null default false,
  unique (plan_id, date, slot)
);

create index meal_plan_slots_plan_idx on public.meal_plan_slots (plan_id);

create table public.meal_plan_slot_recipes (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.meal_plan_slots(id) on delete cascade,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  scaled_servings integer,
  position integer not null default 0,
  unique (slot_id, recipe_id)
);

create index meal_plan_slot_recipes_slot_idx on public.meal_plan_slot_recipes (slot_id);

create table public.meal_plan_day_notes (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.meal_plans(id) on delete cascade,
  date date not null,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (plan_id, date)
);

create index meal_plan_day_notes_plan_idx on public.meal_plan_day_notes (plan_id);

-- ---------------------------------------------------------------------------
-- Shopping
-- ---------------------------------------------------------------------------

create table public.aisles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0
);

create table public.ingredient_aisle_map (
  item_canonical text primary key,
  aisle_id bigint not null references public.aisles(id) on delete cascade
);

-- Per-plan generated shopping-list snapshots. items_json holds the precomputed
-- aisle-grouped aggregate so the per-plan list survives recipe edits.
create table public.shopping_lists (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.meal_plans(id) on delete cascade,
  generated_at timestamptz not null default now(),
  items_json jsonb not null
);

create index shopping_lists_plan_idx on public.shopping_lists (plan_id);

-- Recipes the user has explicitly added to the standalone global shopping list.
create table public.shopping_list_recipes (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  scaled_servings integer,
  from_plan_id bigint references public.meal_plans(id) on delete set null,
  added_at timestamptz not null default now()
);

create index shopping_list_recipes_added_idx on public.shopping_list_recipes (added_at);
create index shopping_list_recipes_from_plan_idx on public.shopping_list_recipes (from_plan_id);

-- Free-form items typed into the global shopping list (e.g. "paper towels").
create table public.shopping_list_items (
  id bigint generated by default as identity primary key,
  name text not null,
  quantity double precision,
  unit text,
  aisle text not null default 'Other',
  is_checked boolean not null default false,
  added_at timestamptz not null default now(),
  checked_at timestamptz
);

create index shopping_list_items_added_idx on public.shopping_list_items (added_at);

-- Per-aggregate-item checked state (item_id is a deterministic hash of the
-- canonical ingredient name + unit family) so checkmarks survive list refreshes.
create table public.shopping_list_checks (
  item_id text primary key,
  is_checked boolean not null default false,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- Single shared account: any signed-in user can read/write everything.
-- Anon role is denied. Service role bypasses RLS automatically.
-- ---------------------------------------------------------------------------

alter table public.recipes               enable row level security;
alter table public.recipe_ingredients    enable row level security;
alter table public.recipe_steps          enable row level security;
alter table public.categories            enable row level security;
alter table public.recipe_categories     enable row level security;
alter table public.meal_plans            enable row level security;
alter table public.meal_plan_slots       enable row level security;
alter table public.meal_plan_slot_recipes enable row level security;
alter table public.meal_plan_day_notes   enable row level security;
alter table public.aisles                enable row level security;
alter table public.ingredient_aisle_map  enable row level security;
alter table public.shopping_lists        enable row level security;
alter table public.shopping_list_recipes enable row level security;
alter table public.shopping_list_items   enable row level security;
alter table public.shopping_list_checks  enable row level security;

do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'recipes', 'recipe_ingredients', 'recipe_steps',
      'categories', 'recipe_categories',
      'meal_plans', 'meal_plan_slots', 'meal_plan_slot_recipes', 'meal_plan_day_notes',
      'aisles', 'ingredient_aisle_map',
      'shopping_lists', 'shopping_list_recipes', 'shopping_list_items', 'shopping_list_checks'
    ])
  loop
    execute format(
      'create policy %I_authenticated_all on public.%I for all to authenticated using (true) with check (true)',
      t, t
    );
  end loop;
end $$;
